name: Update data file

on:
  # every hour or manual trigger
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/update.yml

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Generate data
        run: |
          python scripts/generate.py https://mastodon.social/@graicprints.rss src/routes/data.json

      - name: Check for Modified Files
        id: git-check
        run: echo modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true") >> $GITHUB_OUTPUT

      - name: Generate rss feed
        if: steps.git-check.outputs.modified == 'true'
        run: |
          python scripts/rss.py src/routes/data.json static/feed

      - name: Commit Latest Release Version
        if: steps.git-check.outputs.modified == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update data file
          file_pattern: 'src/routes/data.json static/feed'